/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.info;

import com.topfield.dao.NotificationDao;
import com.topfield.daoImpl.NotificationDaoImpl;
import com.topfield.modal.Notification;
import com.topfield.settings.FrameSettings;
import com.topfield.utilities.BrowserURLLink;
import com.topfield.utilities.ImageConversion;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Murali
 */
public class SingleNote extends javax.swing.JPanel {

    /**
     * Creates new form SingleNote
     */
    
    private Notification note;
    
    public SingleNote(Notification note) {
        initComponents();
        this.note = note;
        
        setHeading(note.getTitle());
        setDescription(note.getDescription());
        setDate(note.getActivedate());
        setIcon(note.getImageLink());
        
        

    }
    
    public void setHeading(String heading){
    jLabel2.setText(heading);
    }
    
    public void setDescription(String des){
    jTextArea1.setText(des);
    }
    
    public void setDate(String Date){
    jLabel4.setText(Date);
    }
    
    public void setIcon(String url){
      
        if (url.contentEquals("N/A")) {    
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(FrameSettings.getImageSelPath()+"STEM_Icons_01_Reminder.png")));
        }else {
            
           jLabel1.setIcon(ImageConversion.setImageSizeExternal(note.getImageLink(), 140, 140));
            
        }
   
     
    }
    

    
    public static void main(String[] args) {
      
       NotificationDao noteDao  = new NotificationDaoImpl();
        
      JFrame frame = new JFrame("Swing Tester");
      frame.setLayout(new BorderLayout());
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      frame.add(new JScrollPane(new SingleNote((noteDao.findById(1)))));
      //frame.setLayout(new BorderLayout());
      frame.setSize(560, 300);      
      frame.setLocationRelativeTo(null);  
      frame.setVisible(true);     

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coachspecs/images/blue/STEM_Icons_01_Reminder.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Headings");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setText("20-01-2020");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hurricane Alex was the first Atlantic hurricane to occur in January since Hurricane Alice of 1954–1955. Alex originated as a non-tropical low near the Bahamas on January 7, 2016. Initially traveling northeast, the system passed by Bermuda on January 8 before turning southeast and deepening. It briefly acquired hurricane-force winds by January 10, then weakened slightly before curving towards the east and later northeast. Acquiring more tropical weather characteristics over time, the system transitioned into a subtropical cyclone well south of the Azores on January 12, becoming the first North Atlantic tropical or subtropical cyclone in January since Tropical Storm Zeta of 2005–2006. Alex continued to develop tropical features while turning north-northeast, and transitioned into a fully tropical cyclone on January 14. The cyclone peaked in strength as a Category 1 hurricane on the Saffir–Simpson scale with maximum sustained winds of 85 mph (140 km/h) and a central pressure of 981 mbar (hPa; 28.97 inHg). Alex weakened to a high-end tropical storm before making landfall on Terceira Island on January 15. By that time, the storm was losing its tropical characteristics; it fully transitioned back into a non-tropical cyclone several hours after moving away from the Azores. Alex ultimately merged with another cyclone over the Labrador Sea on January 17.\n\nThe precursor cyclone to Hurricane Alex brought stormy conditions to Bermuda from January 7 to 9. On its approach, the hurricane prompted hurricane and tropical storm warnings and the closure of schools and businesses for the Azores. Alex brought gusty winds and heavy rain to the archipelago, though structural damage was generally minor. One person died of a heart attack because the inclement weather prevented them from being transported to hospital in time.");
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("More Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (note.getSourceLink().contentEquals("N/A")) {
            JOptionPane.showMessageDialog(this,"Short massage only. No More Details");
        }else {
            BrowserURLLink.open(note.getSourceLink());
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
