/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.popup;

import com.topfield.calculators.faulttree.FaultTreeEquations;
import com.topfield.dao.CalcFunctionsDao;
import com.topfield.dao.CalcfileDao;
import com.topfield.dao.SpfhdrDao;
import com.topfield.daoImpl.CalcFunctionsDaoImpl;
import com.topfield.daoImpl.CalcfileDaoImpl;
import com.topfield.daoImpl.SpfhdrDaoImpl;
import com.topfield.datamodel.Item;
import com.topfield.modal.CalcFunctions;
import com.topfield.modal.Calcfile;
import com.topfield.modal.Spfhdr;
import com.topfield.utilities.NumberConversion;
import com.topfield.utilities.ScientificNotation;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;


/**
 *
 * @author Murali
 */
public class FTABasicPopup extends javax.swing.JPanel {
    
   private CalcfileDao CalcfileDao = new CalcfileDaoImpl(); 
   private ScientificNotation sciNotation = new ScientificNotation("0.00E0");
   private Calcfile calcfileRef;
   private Spfhdr spfhdr;
   private List<Integer> addedList;
   private boolean editable;
   private boolean bottomUp;
   private  List<Calcfile> calcFileData;
   private Calcfile clfile;
    /**
     * Creates new form FTABasicPopup
     */
   
    public FTABasicPopup() {
 
        intializer();
        jTextField1.setForeground(Color.BLUE);
        clearAll();
        
    }


   
   
    public FTABasicPopup(Spfhdr spfhdr,List<Integer> addedList,boolean editable,boolean bottomUp) {
        this.spfhdr =  spfhdr;
        this.addedList = addedList;
        this.editable = editable;
        this.bottomUp = bottomUp;
        
        intializer();
        clearAll();

    }
    
    public void intializer(){
    
        String[] failure = new String[]{"per hour", "per year", "per million hour","per billion hours (FIT)"};
        int[] failureid = new int[]{1,8760,1000000,1000000000};
        String[] time = new String[]{"hours" , "weeks", "months", "years", "million hours"};
        int[] timeid = new int[]{1,168,730,8760,1000000};  //720
        
        initComponents();
        hideTimePeriodRow();
        setPreferredSize(new Dimension(600, 280));

        
        for (int i = 0; i < failure.length; i++) {
            jComboBox2.addItem(new Item(failureid[i], failure[i]));
        }
        
        for (int i = 0; i < timeid.length; i++) {
            jComboBox4.addItem(new Item(timeid[i], time[i]));
        }
        

        setCalcFileData(false,bottomUp);
        bottomUpSettings();
        intialSettings();
        //jComboBox5.setEnabled(!editable);
           //((JTextField)jComboBox2.getEditor().getEditorComponent()).setDisabledTextColor(Color.BLACK);
           //((JTextField)jComboBox2.getEditor().getEditorComponent()).setForeground(Color.BLACK);
           //jComboBox2.getEditor().getEditorComponent().setBackground(Color.BLACK);
        
       UIManager.getDefaults().put("ComboBox.disabledForeground", new Color(112, 123, 124  ) );
    
    
    }

    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    public List<Integer> getAddedList() {
        return addedList;
    }

    public void setAddedList(List<Integer> addedList) {
        this.addedList = addedList;
    }
    
    public Spfhdr getSpfhdr() {
        return spfhdr;
    }

    public void setSpfhdr(Spfhdr spfhdr) {
        this.spfhdr = spfhdr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();

        jLabel7.setText("Probability :-");

        jLabel9.setText("Probability :-");

        jLabel11.setText("/ hr");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(56, 20));

        jLabel1.setText("Component Id :");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jTextField1.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 51, 102));
        jTextField1.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        jTextField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Component Name :");

        jLabel3.setText("Data Type  :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fixed Probability", "Non Repairable Failure", "Revealed Failure", "Unrevealed Failure" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Reference :");

        jLabel5.setText("Probability :");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel6.setText("Proof Test Interval :");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jLabel8.setText("/ hr");

        jLabel10.setText(" hr");

        jLabel12.setText("/ hr");

        jLabel13.setText("/ hr");

        jComboBox2.setForeground(new java.awt.Color(0, 0, 102));
        jComboBox2.setEnabled(false);
        jComboBox2.setPreferredSize(new java.awt.Dimension(56, 20));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox2KeyReleased(evt);
            }
        });

        jComboBox4.setPreferredSize(new java.awt.Dimension(56, 20));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jLabel14.setText("Component :");

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(0, 0, 102));
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 51, 102));
        jTextField5.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        checkbox1.setLabel("Edit CalcFile Data");
        checkbox1.setVisible(false);
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, 0, 154, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5)
                                            .addComponent(jTextField1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(14, 14, 14))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
 
        String selection = (String) evt.getItem();
        
        if (calcfileRef == null) {
            calcfileRef = getFunctionalComponents();
        }
        

        if (selection.contentEquals("Fixed Probability")) {
           intialSettings();
        } else if (selection.contentEquals("Non Repairable Failure")) {
            jLabel5.setText("Frequency : ");
            setUnits("/ hr", "");
            hideTimePeriodRow();
        } else if (selection.contentEquals("Revealed Failure")) {
            jLabel5.setText("Failure rate : ");
            jLabel6.setText("Repair Time : ");
            setUnits("/ hr", "hr");
            showTimePeriodRow();
        } else if (selection.contentEquals("Unrevealed Failure")) {
            jLabel5.setText("Failure rate : ");
            jLabel6.setText("Proof Test Interval : ");
            setUnits("/ hr", "");
            showTimePeriodRow();
        }

        setFailureRate(bottomUp);
        //setFrequency(FaultTreeEquations.FailureRateConveter(getDataType(), calcfileRef.getFailureRate(), calcfileRef.getFMPercentage() ,calcfileRef.getURPercentage()));

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        Item selItem = (Item)evt.getItem();
        
        jLabel12.setText(NumberConversion.scientificNotation(unitsConverter(jTextField3.getText(), selItem.getId(), false), 2));
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
       
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jComboBox2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyReleased
      
    }//GEN-LAST:event_jComboBox2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
       Item selItem = (Item)jComboBox2.getSelectedItem();
        
        System.out.println("jTextField3.getText() - "+jTextField3.getText());
        jLabel12.setText(NumberConversion.scientificNotation(unitsConverter(jTextField3.getText(), selItem.getId(), false), 2));
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        Item selItem = (Item)evt.getItem();
        
        jLabel13.setText(NumberConversion.scientificNotation(unitsConverter(jTextField4.getText(), selItem.getId(), true), 2));
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        Item selItem = (Item)jComboBox4.getSelectedItem();
        
        jLabel13.setText(NumberConversion.scientificNotation(unitsConverter(jTextField4.getText(), selItem.getId(), true), 2));
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        Item item = (Item) evt.getItem();
        setCalcData(item.getId());
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setCalcFileData(false,bottomUp);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        int a=JOptionPane.showConfirmDialog(null,"Are you sure you want edit calc Data? \n The changes will apply to all calculators");

        
        if(a==JOptionPane.YES_OPTION){
             calcEdit(true);
            System.out.println("kjlkjlkj");
        } else{
            calcEdit(false);
        }

    }//GEN-LAST:event_checkbox1ItemStateChanged

    
    public Calcfile findEleById(int id){
    
     List<Calcfile> res = calcFileData.stream().filter(calc -> (calc.getCalcId()==id)).collect(Collectors.toList());
     return res.isEmpty() ? null :res.get(0);
    
    }
    
    public void setCalcData(int calcId){
      //calcfileRef = CalcfileDao.findById(calcId);
      calcfileRef = findEleById(calcId);
     
        if (calcfileRef != null) {
            
            setComponentName(calcfileRef.getCompId());
            setDescription(calcfileRef.getComponents());
        
            setFailureRate(bottomUp);
            
        }
        

    }
    
    public void setFailureRate(boolean bottomUp){
    
        if (!bottomUp) {
            if ((getDataType().contentEquals("Fixed Probability"))) {
                 setProbability(calcfileRef.getProbability());
            } else {
                 //setFrequency(calcfile.getFailureRate()*calcfile.getFMPercentage()*calcfile.getURPercentage());
                 setFrequency(FaultTreeEquations.FailureRateConveter(getDataType(), calcfileRef.getFailureRate(), calcfileRef.getFMPercentage() ,calcfileRef.getURPercentage()));
            }
        }
        
    
    }
    
    
    public static void main(String[] args) {
        SpfhdrDao spfhdrDao = new SpfhdrDaoImpl();
        JFrame frame = new JFrame("DropDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setContentPane(new FTABasicPopup(spfhdrDao.findById(10),new ArrayList<Integer>(),true,true));

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    
    
    public Calcfile getFunctionalComponents(){
     Calcfile clf;
        if (bottomUp) {
            
            clf = editable? clfile: new Calcfile();
            clf.setCompId(getComponentName());
            clf.setComponents(getDescription());
            clf.setFailureRate(getFrequency());
            clf.setProbability(getProbability());
            
        }else{
                if (jComboBox5.getSelectedItem()!= null) {
                    clf = CalcfileDao.findById(((Item)jComboBox5.getSelectedItem()).getId());
                } else {
                    clf = null;
                }
        }
        return clf;     
    } 
    
    public void setFunctionalComponents(int calcId){
        Calcfile cfile = CalcfileDao.findById(calcId);
        if (bottomUp) {
            clfile = cfile;
           /* setComponentName(clfile.getCompId());
            setDescription(clfile.getComponents());
            setFrequency(clfile.getFailureRate());
            setProbability(clfile.getProbability());*/
        }else{
            Item functionalComponents = new Item(cfile.getCalcId(), cfile.getComponents());
            jComboBox5.setSelectedItem(functionalComponents);
        }
  
    } 
    
    public void setFunctionalComponents(Calcfile cfile){
        if (bottomUp) {
            clfile = cfile;
            setComponentName(clfile.getCompId());
            setDescription(clfile.getComponents());
            setFrequency(clfile.getFailureRate());
            setProbability(clfile.getProbability());
        }else{
            Item functionalComponents = new Item(cfile.getCalcId(), cfile.getComponents());
            jComboBox5.setSelectedItem(functionalComponents);
        }

    }  
    
    
    
    public String getComponentName() {
        return jTextField1.getText();
    }

    public void setComponentName(String Componentname) {
        this.jTextField1.setText(Componentname);
    }
    
    public String getDescription() {
        return jTextField5.getText();
    }

    public void setDescription(String description) {
        this.jTextField5.setText(description);
    }


    public String getDataType() {
        return jComboBox1.getSelectedItem() + "";
    }

    public void setDataType(String dataType) {
        this.jComboBox1.setSelectedItem(dataType);
    }

    public String getReference() {
        return jTextField2.getText();
    }

    public void setReference(String reference) {
        this.jTextField2.setText(reference);
    }

    public double getFrequency() {
        double res = 0.0;
        if (!(getDataType().contentEquals("Fixed Probability"))) {
            res = NumberConversion.NVLDouble((jLabel12.getText()),0); //jTextField3.getText()
        }

        return res;
    }

    public void setFrequency(double fre) {
       
        if (!(getDataType().contentEquals("Fixed Probability"))) {
            jTextField3.setText(sciNotation.sciFormatString(fre + ""));
            jLabel12.setText(jTextField3.getText());
        }
        
    }

    public double getProbability() {
        double res = 0.0;

        if ((getDataType().contentEquals("Fixed Probability"))) {
            res = NumberConversion.NVLDouble(jLabel12.getText(), 0); //jTextField3.getText()
        }

        return res;

    }

    public void setProbability(double pro) {
       if ((getDataType().contentEquals("Fixed Probability"))) {
        jTextField3.setText(pro + "");
        jLabel12.setText(pro + "");
       }
    }

    public double getRepairTime() {
        double res = 0.0;
        if (!(getDataType().contentEquals("Fixed Probability"))) {
            res = NumberConversion.NVLDouble(jLabel13.getText(),0); //jTextField4.getText()
        }

        return res;
    }

    public void setRepairTime(double repairTime) {
        if (!(getDataType().contentEquals("Fixed Probability"))) {
        jTextField4.setText(repairTime + "");
        jLabel13.setText(repairTime + "");
        }
    }





    public void hideTimePeriodRow() {

        jLabel6.setVisible(false);
        jTextField4.setVisible(false);
        jTextField4.setText("0.0");
        jLabel10.setVisible(false);
        jLabel13.setVisible(false);
        jComboBox4.setVisible(false);

    }

    public void showTimePeriodRow() {

        jLabel6.setVisible(true);
        jTextField4.setVisible(true);
        jLabel10.setVisible(true);
        jLabel13.setVisible(true);
        jComboBox4.setVisible(true);
    }
    
    
    public double unitsConverter(String value,int unitVal,boolean divide){
    double res=0.0;
    
            if (divide) {
                res = NumberConversion.NVLDouble(value, 0)/unitVal;
            } else {
                res = NumberConversion.NVLDouble(value, 0)*unitVal;
            }

    return res;
    }
    
    public void clearAll(){
          checkbox1.setVisible(false);
          if (jComboBox5.getItemCount() >0) {
            jComboBox5.setSelectedIndex(0);
           }

          setComponentName("");
          setDescription("");
          setReference("");
          jComboBox1.setSelectedIndex(0);
          setFrequency(0.0);
          setProbability(0.0);
          setRepairTime(0.0);
          jComboBox4.setSelectedIndex(0);
          //jComboBox5.setEnabled(!editable);
          setCalcFileData(false,bottomUp);
          // CalcEditSettings
          calcEdit(bottomUp);
         
    }
    
    public void calcEdit(boolean tick){
    
         if(tick){
            jTextField1.setEditable(true);
            jTextField1.setOpaque(true);
            jTextField3.setEditable(true);
            jTextField3.setOpaque(true);
            jTextField5.setEditable(true);
            jTextField5.setOpaque(true);
            jComboBox2.setEnabled(true);
            System.out.println("kjlkjlkj");
        } else{
            checkbox1.setState(false);
            jTextField1.setEditable(false);
            jTextField1.setOpaque(false);
            jTextField3.setEditable(false);
            jTextField3.setOpaque(false);
            jTextField5.setEditable(false);
            jTextField5.setOpaque(false);
            jComboBox2.setEnabled(false);
        }
    
    
    }
    
    public void setCalcFileData(boolean refersh,boolean bottomUp){
       
        if (!bottomUp) {
            
            if (refersh || calcFileData==null) {
                calcFileData  = CalcfileDao.getAllCalcfileByCalcFun(spfhdr.getSpfid().getCalcFunId());
                //CalcfileDao.refresh(calcFileData);
            }

               jComboBox5.removeAllItems();
               for (Calcfile calcfile : calcFileData)  {
                   if (/*editable || */!addedList.contains(calcfile.getCalcId())) {
                       Item  itemSel2 = new Item(calcfile.getCalcId(), calcfile.getComponents());
                       jComboBox5.addItem(itemSel2);
                   }
               }
            
        }
    }
    
    public void bottomUpSettings(){
        jLabel14.setVisible(!bottomUp);
        jComboBox5.setVisible(!bottomUp);
        //jLabel15.setVisible(bottomUp);
        //jTextField6.setVisible(bottomUp);
        
    }
    
    public void setUnits(String pro,String time){
      jLabel8.setText(pro);
      jLabel10.setText(time);
      jComboBox2.setVisible(!pro.equals(""));
       
    }

    public void intialSettings(){
       jLabel5.setText("Probability : ");
       setUnits("", "");
       hideTimePeriodRow();
    }
    
    public boolean getCalcEdit(){
      return checkbox1.getState();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Item> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<Item> jComboBox4;
    private javax.swing.JComboBox<Item> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
