/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.popup;

import com.topfield.calculators.ccf.CCFCurd;
import com.topfield.dao.CalcFunctionsDao;
import com.topfield.dao.CalcfileDao;
import com.topfield.dao.SpfhdrDao;
import com.topfield.daoImpl.CalcFunctionsDaoImpl;
import com.topfield.daoImpl.CalcfileDaoImpl;
import com.topfield.daoImpl.SpfhdrDaoImpl;
import com.topfield.datamodel.FaulttreeNode;
import com.topfield.datamodel.Item;
import com.topfield.modal.CalcFunctions;
import com.topfield.modal.Calcfile;
import com.topfield.modal.Spfhdr;
import com.topfield.themes.CheckBoxList;
import com.topfield.user.UserInfo;
import com.topfield.utilities.NumberConversion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author Murali
 */
public class InsertCCFBottomUp extends javax.swing.JPanel {
    
    private CheckBoxList jBoxList;
    private CalcfileDao CalcfileDao = new CalcfileDaoImpl(); 
    private  SpfhdrDao spfhdrDao = new SpfhdrDaoImpl();     
    private CCFCurd ccfCurd= new CCFCurd();
    private List<Spfhdr> ccfHdr;
    private double failmodePre;
    private double unreveledPre;
    private final List<FaulttreeNode> allNodes;

    /**
     * Creates new form InsertCCF
     */
    public InsertCCFBottomUp(List<FaulttreeNode> allNodes,List<String>  sel) {
        initComponents();
        
         ccfHdr =  spfhdrDao.getAllSpfhdrByPro(UserInfo.getInstance().getProjectNo(), "CCF", UserInfo.getInstance().getuser().getUsername());
       /*calcComp = CalcfileDao.getAllCalcfileByCalcFun(calcFunctions.getCalcFunId());
       //ccfHdr =  spfhdrDao.getAllSpfhdrByProFun(UserInfo.getInstance().getProjectNo(), "CCF", UserInfo.getInstance().getuser().getUsername(),calcFunctions.getCalcFunId());
      
         ArrayList<Item> checkBoxList = new ArrayList<>();
        checkBoxList.add(new Item(1,"Test 1"));
         checkBoxList.add(new Item(2,"Test 2"));
          checkBoxList.add(new Item(3,"Test 3"));
           checkBoxList.add(new Item(4,"Test 4"));
            checkBoxList.add(new Item(5,"Test 5"));
             checkBoxList.add(new Item(6,"Test 6"));*/
       
             
        jBoxList  =   new CheckBoxList(getComponentList(allNodes),sel); 
        jBoxList.setPreferredSize(new Dimension(380,200));
        
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setPreferredSize(new Dimension(400,200));
        jPanel1.add(new JScrollPane( jBoxList));
        
        
        for (Spfhdr spfhdrCCF : ccfHdr) {
            jComboBox1.addItem(new Item(spfhdrCCF.getSpfhdrid(), spfhdrCCF.getDescriptions()));
        }
        
       // jLabel4.setText("");
        this.allNodes = allNodes;
       

        
    }
    
    public CheckBoxList getCheckBoxList(){
    
        return jBoxList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setText("Select components");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jLabel2.setText("Select CCF");

        jComboBox1.setMinimumSize(new java.awt.Dimension(56, 20));
        jComboBox1.setPreferredSize(new java.awt.Dimension(56, 20));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText(" Beta factor");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("jLabel4");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Calculate CCF Failure Rate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("................");

        jLabel6.setText("Description");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(103, 103, 103)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE)))))
                        .addGap(37, 37, 37)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
      
       // ArrayList<Integer> list = jBoxList.getSelectedItems();
        //Double res=0.0;
        Double betaFactor=0.0;
        
       /* for (Integer integer : list) {
            res = res+ getCalcfileById(integer).getFailureRate();
        }
        
        res = res/list.size();*/
        
        betaFactor = getBeatFactorByCcfHdr(getCCFhdrById(((Item)jComboBox1.getSelectedItem()).getId()));
        
        jLabel4.setText(betaFactor.toString());
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel5.setText(NumberConversion.scientificNotation(getCCFFailureRate(), 4));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    public String getDescription(){
    
    return jTextField1.getText();
    } 
    
    public void setDescription(String des){
    
     jTextField1.setText(des);
    } 
   
    
    public Spfhdr getCCFHdr(){
    
     return getCCFhdrById(((Item)jComboBox1.getSelectedItem()).getId());
    } 
    
     public String getCCFHdrString(){
      Item item = ((Item)jComboBox1.getSelectedItem());
     return item.getId()+"#"+item.getDescription();
    } 
    
    public void setCCFHdr(String ccfHdrId,String des){
    
     jComboBox1.setSelectedItem(new Item(NumberConversion.NVL(ccfHdrId, -1), des));
    } 
    
    
    public ArrayList<Item> getComponentList(List<FaulttreeNode> allNodes){
    
        ArrayList<Item> checkBoxList = new ArrayList<>();
        
        for (FaulttreeNode node : allNodes)  {
                Item  itemSel2 = new Item(node.hashCode(), node.getDescription()+node.getCompId());
                checkBoxList.add(itemSel2);
            
        }
    
    
    return checkBoxList;
    
    }
    
    
    public FaulttreeNode getFaulttreeNodeById(int id){
    
       FaulttreeNode  node ; 
 
       Optional<FaulttreeNode> matchingObject = allNodes.stream().
       filter(c -> c.hashCode()== id).
       findFirst();
       
       node =matchingObject.get();
       failmodePre = node.getFrequency();
       unreveledPre = 1.0;
    
       return node;
    }
    
    public Spfhdr getCCFhdrById(int ccfHdrId){
    
       Optional<Spfhdr> matchingObject = ccfHdr.stream().
       filter(c -> c.getSpfhdrid()== ccfHdrId).
       findFirst();
    
       return matchingObject.get();
    }
    
    
    public Double getBeatFactorByCcfHdr(Spfhdr Spfhdr){

       return NumberConversion.NVLDouble(ccfCurd.getJSONProperty(Spfhdr.getProsettings(), "results", "betaFactor"), 0);
    }
    
    
    public Double getCCFFailureRate(){
    Double res =0.0;
    Double betaFactor=0.0;
    ArrayList<Integer> list = jBoxList.getSelectedItems();
        
        
        for (Integer integer : list) {
            res = res+ getFaulttreeNodeById(integer).getFrequency();
        }
        
        //res = res/list.size();
        
        betaFactor = getBeatFactorByCcfHdr(getCCFhdrById(((Item)jComboBox1.getSelectedItem()).getId()));
    
    return res*betaFactor;
    }
    
    public static void main(String[] args) {
        
         CalcFunctionsDao calcFunctionsDao = new CalcFunctionsDaoImpl();
        JFrame frame = new JFrame("DropDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 
              List<String> contanis = new ArrayList<>();
              contanis.add("Test 4");
        //frame.setContentPane(new InsertCCFBottomUp(calcFunctionsDao.findById(16),contanis));
 
        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Item> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the failmodePre
     */
    public double getFailmodePre() {
        return failmodePre;
    }

    /**
     * @return the unreveledPre
     */
    public double getUnreveledPre() {
        return unreveledPre;
    }
}
