/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.popup;

import com.topfield.dao.CalcFunctionsDao;
import com.topfield.dao.MainProductGroupDao;
import com.topfield.dao.MpgHdrDao;
import com.topfield.dao.SpfhdrDao;
import com.topfield.dao.StandardsDao;
import com.topfield.daoImpl.CalcFunctionsDaoImpl;
import com.topfield.daoImpl.MainProductGroupDaoImpl;
import com.topfield.daoImpl.MpgHdrDaoImpl;
import com.topfield.daoImpl.SpfhdrDaoImpl;
import com.topfield.daoImpl.StandardsDaoImpl;
import com.topfield.datamodel.Item;
import com.topfield.modal.CalcFunctions;
import com.topfield.modal.MainProductGroup;
import com.topfield.modal.Mpghdr;
import com.topfield.modal.Spfhdr;
import com.topfield.modal.Standards;
import com.topfield.user.UserInfo;
import javax.swing.JFrame;

/**
 *
 * @author Murali
 */
public class SpfcPopup extends javax.swing.JPanel {
    
    private MainProductGroupDao mpgDao = new MainProductGroupDaoImpl();   
    private SpfhdrDao spfDao = new SpfhdrDaoImpl();
    private MpgHdrDao mpgHdrDao = new MpgHdrDaoImpl();
    private CalcFunctionsDao calcFunctionsDao = new CalcFunctionsDaoImpl(); 
    private StandardsDao stdDao = new StandardsDaoImpl();
    
     private boolean modify;
     private String calculator;

    /**
     * Creates new form SpfPopup
     */
    public SpfcPopup(boolean modify,String calculator) {
        initComponents();
        
        this.modify =modify;
        this.calculator = calculator;
        
        /*for (MainProductGroup mainProductGroup : mpgDao.getAllMPG()) {
            jComboBox1.addItem(new Item(mainProductGroup.getMpgId(), mainProductGroup.getMpgDescription())); 
        }*/
        
        for (Mpghdr mpgType1 : mpgHdrDao.getSummaryFMEAHERByMPG(UserInfo.getInstance().getProjectNo(),"CMM", UserInfo.getInstance().getuser().getUsername())) {
             jComboBox1.addItem(new Item(mpgType1.getFmeaComponent().getMpgId(), mpgType1.getFmeaComponent().getMpgDescription()));
        }
        
        for (Standards standards : stdDao.findByCalculator(calculator)) {
            //comboBox.addItem(new Item(standards.getId(), standards.getCode()));
            jComboBox3.addItem(new Item(standards.getId(), standards.getCode()));
        }
        
        if (modify) {
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("Descriptions");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("MPG Name");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("SPF Name");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Standards");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Comments");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox2, 0, 188, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 188, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

     MainProductGroup main = mpgDao.FindById(((Item)jComboBox1.getSelectedItem()).getId());
     Mpghdr mpgHdr = mpgHdrDao.getAllFMEAHDRByMPGOne(main.getMpgId(), "CMM", UserInfo.getInstance().getProjectNo(), UserInfo.getInstance().getuser().getUsername());
             
             //spfDao.getAllSpfhdrByMPG(main.getMpgId(), calculator, UserInfo.getInstance().getProjectNo(), UserInfo.getInstance().getuser().getUsername());

        jComboBox2.removeAllItems();
        
        if (mpgHdr != null) {

        for ( CalcFunctions calcFunctions: calcFunctionsDao.getAllCalcFunctionsByMpgheader(mpgHdr.getMpghdrid())) {
            Item  itemSel2 = new Item(calcFunctions.getCalcFunId(), calcFunctions.getCalcFunction());
            jComboBox2.addItem(itemSel2);

        }
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public String getDescriptions(){
    return jTextField1.getText();
    }
    
      
    public void setDescriptions(String descriptions){
    jTextField1.setText(descriptions);
    }
    
    
    public Item getMPG(){
    return (Item)jComboBox1.getSelectedItem();
    }
    
      
    public void setMPG(Item mpg){
     jComboBox1.setSelectedItem(mpg);
    }
    
    public CalcFunctions getSPF(){
    return calcFunctionsDao.findById(((Item)jComboBox2.getSelectedItem()).getId());
    }
    
      
    public void setSPF(CalcFunctions spf){
     jComboBox2.setSelectedItem(new Item(spf.getCalcFunId(), spf.getCalcFunction()));
    }
    
    public Item getStandards(){
    return (Item)jComboBox3.getSelectedItem();
    }
    
      
    public void setStandards(Item standards){
     jComboBox3.setSelectedItem(standards);
    }
    
    public String getComments(){
    return jTextArea1.getText();
    }
    
      
    public void setComments(String comments){
    jTextArea1.setText(comments);
    }
    
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    
   public static void main(String[] args) {
        
                
        JFrame frame = new JFrame("DropDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 

        frame.setContentPane(new SpfPopup(false,"RBD"));
 
        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Item> jComboBox1;
    private javax.swing.JComboBox<Item> jComboBox2;
    private javax.swing.JComboBox<Item> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
