/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.popup;

import com.topfield.dao.CalcFunctionsDao;
import com.topfield.dao.MainProductGroupDao;
import com.topfield.dao.MpgHdrDao;
import com.topfield.dao.SpfhdrDao;
import com.topfield.dao.StandardsDao;
import com.topfield.daoImpl.CalcFunctionsDaoImpl;
import com.topfield.daoImpl.MainProductGroupDaoImpl;
import com.topfield.daoImpl.MpgHdrDaoImpl;
import com.topfield.daoImpl.SpfhdrDaoImpl;
import com.topfield.daoImpl.StandardsDaoImpl;
import com.topfield.datamodel.Item;
import com.topfield.modal.CalcFunctions;
import com.topfield.modal.MainProductGroup;
import com.topfield.modal.Mpghdr;
import com.topfield.modal.Spfhdr;
import com.topfield.modal.Standards;
import com.topfield.user.UserInfo;
import javax.swing.JFrame;

/**
 *
 * @author Murali
 */
public class SpfPopup extends javax.swing.JPanel {
    
    private MainProductGroupDao mpgDao = new MainProductGroupDaoImpl();   
    private SpfhdrDao spfDao = new SpfhdrDaoImpl();
    private MpgHdrDao mpgHdrDao = new MpgHdrDaoImpl();
    private CalcFunctionsDao calcFunctionsDao = new CalcFunctionsDaoImpl(); 
    private StandardsDao stdDao = new StandardsDaoImpl();
    private boolean bottomUp = true;
    
     private boolean modify;
     private String calculator;

    /**
     * Creates new form SpfPopup
     */
    public SpfPopup(boolean modify,String calculator) {
        initComponents();
        
        this.modify =modify;
        this.calculator = calculator;
        
        for (MainProductGroup mpg : mpgDao.getAllMPGByAdminUser(UserInfo.getInstance().getuser().getUsername())) {
                jComboBox4.addItem(new Item(mpg.getMpgId(), mpg.getMpgDescription()+" ("+mpg.getMpgRef()+")"));
        }
        
        jComboBox1.addItem(new Item(-1, "<- New File ->"));
        for (Mpghdr mpgType1 : mpgHdrDao.getSummaryFMEAHERByMPG(UserInfo.getInstance().getProjectNo(),"CMM", UserInfo.getInstance().getuser().getUsername())) {
             //jComboBox1.addItem(new Item(mpgType1.getFmeaComponent().getMpgId(), mpgType1.getFmeaComponent().getMpgDescription()));
             jComboBox1.addItem(new Item(mpgType1.getMpghdrid(), mpgType1.getDescriptions()));
        }
        
        for (Standards standards : stdDao.findByCalculator(calculator)) {
            //comboBox.addItem(new Item(standards.getId(), standards.getCode()));
            jComboBox3.addItem(new Item(standards.getId(), standards.getCode()));
        }
        
        if (modify) {
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
        }
        
         funtionSwitch();
         //jLabel1.setText(calculator+" Name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jLabel1.setText("Function Name :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select CMM :");

        jComboBox1.setMinimumSize(new java.awt.Dimension(31, 20));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Function :");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Standards :");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Comments :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Select MPG :");

        jLabel7.setText("Function Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       setCalMpgSel();
       funtionSwitch();
     //MainProductGroup main = mpgDao.FindById(((Item)jComboBox1.getSelectedItem()).getId());
     //Mpghdr mpgHdr = mpgHdrDao.getAllFMEAHDRByMPGOne(main.getMpgId(), "CMM", UserInfo.getInstance().getProjectNo(), UserInfo.getInstance().getuser().getUsername());
      
        if (!bottomUp) {
            
     
            Mpghdr mpgHdr = mpgHdrDao.getFMEASById(((Item)jComboBox1.getSelectedItem()).getId());
                    //spfDao.getAllSpfhdrByMPG(main.getMpgId(), calculator, UserInfo.getInstance().getProjectNo(), UserInfo.getInstance().getuser().getUsername());

               jComboBox2.removeAllItems();

               if (mpgHdr != null) {

               for ( CalcFunctions calcFunctions: calcFunctionsDao.getAllCalcFunctionsByMpgheader(mpgHdr.getMpghdrid())) {
                   Item  itemSel2 = new Item(calcFunctions.getCalcFunId(), calcFunctions.getCalcFunction());
                   jComboBox2.addItem(itemSel2);

               }
               }
           
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public String getDescriptions(){
    return jTextField1.getText();
    }
    
      
    public void setDescriptions(String descriptions){
    jTextField1.setText(descriptions);
    }
    
    
    public Item getCalcFile(){
      return (Item)jComboBox1.getSelectedItem();
    }
    
      
    public void setCalcFile(Item mpg){
     jComboBox1.setSelectedItem(mpg);
    }
    
    public CalcFunctions getSPF(){
        
        if (jComboBox2.getSelectedItem() == null) {
             return null; 
        } else {
             return calcFunctionsDao.findById(((Item)jComboBox2.getSelectedItem()).getId());
        }
   
    }
    
      
    public void setSPF(CalcFunctions spf){
     jComboBox2.setSelectedItem(new Item(spf.getCalcFunId(), spf.getCalcFunction()));
    }
    
    public Item getStandards(){
    return (Item)jComboBox3.getSelectedItem();
    }
    
      
    public void setStandards(Item standards){
     jComboBox3.setSelectedItem(standards);
    }
    
    public String getComments(){
    return jTextArea1.getText();
    }
    
      
    public void setComments(String comments){
    jTextArea1.setText(comments);
    }
    
    public void setCalMpgSel(){
    
      if (jComboBox1.getSelectedIndex()==0) {
             //jComboBox1.setEnabled(true);
             jComboBox4.setVisible(true);
             jLabel6.setVisible(true);
             bottomUp =true;
        } else {
            // jComboBox1.setEnabled(false);
             jComboBox4.setVisible(false);
             jLabel6.setVisible(false);
             bottomUp =false;
        }
    
    }
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void funtionSwitch(){
    
        jLabel3.setVisible(!bottomUp);
        jComboBox2.setVisible(!bottomUp);
        
        /*jLabel7.setVisible(bottomUp);
        jTextField2.setVisible(bottomUp);*/
        
        jLabel7.setVisible(false);
        jTextField2.setVisible(false);
        
        if (bottomUp) {
            setJlablel1("Function Name :");
        } else {
             setJlablel1(calculator+" Name :");
        }
    
    }
    
    public String getFuntionName(){
     return /*jTextField2*/jTextField1.getText();
    }
    
    public void setFuntionName(String fun){
     /*jTextField2*/jTextField1.setText(fun);
    }
    
     public int getMpgId() {
      int res=-2;
      
       if (jComboBox4.getSelectedItem() != null) {
           res = ((Item) jComboBox4.getSelectedItem()).getId();
       }
      
      return res;
    }
    
    public MainProductGroup getMpg() {

        if (jComboBox4.getSelectedItem() == null) {
            return null;
        } else {
            return mpgDao.FindById(((Item) jComboBox4.getSelectedItem()).getId());
        }
        
    }
    
    
    public void setMpgObj(MainProductGroup mpg) {
        jComboBox4.setSelectedItem(new Item(mpg.getMpgId(), mpg.getMpgDescription()));
    }

    public void setMpg(int mpgId) {
        MainProductGroup mpg = mpgDao.FindById(mpgId);
        jComboBox4.setSelectedItem(new Item(mpg.getMpgId(), mpg.getMpgDescription()));
    }
    
    public void setJlablel1(String text){
     jLabel1.setText(text);
    }
    
   public static void main(String[] args) {
        
                
        JFrame frame = new JFrame("DropDemo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 

        frame.setContentPane(new SpfPopup(false,"RBD"));
 
        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Item> jComboBox1;
    private javax.swing.JComboBox<Item> jComboBox2;
    private javax.swing.JComboBox<Item> jComboBox3;
    private javax.swing.JComboBox<Item> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
