/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.calculators;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import com.topfield.modal.Components;

/**
 *
 * @author Murali
 */
public class Calculator1_form extends javax.swing.JPanel {

    private String name;
    private JList<Components> componentsList;
    private JList<String> componentList;
   
    /**
     * Creates new form Calculator1_form
     */
    public Calculator1_form(String name,String voting,JList<Components> componentsList,JList<String> componentList ) {
        this.name = name;
        this.componentsList = componentsList;
        this.componentList = componentList;
        //this.index = index;
        initComponents();
        //setBackground(Color.LIGHT_GRAY);
        comboVoting1.setSelectedItem(voting);
        
    }

    /**
     * @return the comboMTTR1
     */
    public String getComboMTTR1() {
        return comboMTTR1.getSelectedItem()+"";
    }

    /**
     * @param comboMTTR1 the comboMTTR1 to set
     */
    public void setComboMTTR1(String comboMTTR1) {
        this.comboMTTR1.setSelectedIndex(Integer.parseInt(comboMTTR1) );
    }

    /**
     * @return the comboPTP1
     */
    public String getComboPTP1() {
        return comboPTP1.getSelectedItem()+"";
    }

    /**
     * @param comboPTP1 the comboPTP1 to set
     */
    public void setComboPTP1(String comboPTP1) {
        this.comboPTP1.setSelectedIndex(Integer.parseInt(comboPTP1));
    }

    /**
     * @return the comboVoting1
     */
    public String getComboVoting1() {
        return comboVoting1.getSelectedIndex()+"";
    }

    /**
     * @param comboVoting1 the comboVoting1 to set
     */
    public void setComboVoting1(int comboVoting1) {
        this.comboPTP1.setSelectedIndex(comboVoting1);
    }

    /**
     * @return the inpCCF1
     */
    public String getInpCCF1() {
        return inpCCF1.getText();
    }

    /**
     * @param inpCCF1 the inpCCF1 to set
     */
    public void setInpCCF1(Double inpCCF1) {
        this.inpCCF1.setText(inpCCF1.doubleValue()+"");
    }

    /**
     * @return the inpDC1
     */
    public String getInpDC1() {
        return inpDC1.getText();
    }

    /**
     * @param inpDC1 the inpDC1 to set
     */
    public void setInpDC1(Double inpDC1) {
        this.inpDC1.setText(inpDC1.doubleValue()+"");
    }

    /**
     * @return the inpLambda1
     */
    public String getInpLambda1() {
        return inpLambda1.getText();
    }

    /**
     * @param inpLambda1 the inpLambda1 to set
     */
    public void setInpLambda1(Double inpLambda1) {
        this.inpLambda1.setText(inpLambda1.doubleValue()+"");
    }

    /**
     * @return the inpLambda2
     */
    public String getInpLambda2() {
        return inpLambda2.getText();
    }

    /**
     * @param inpLambda2 the inpLambda2 to set
     */
    public void setInpLambda2(Double inpLambda2) {
        this.inpLambda2.setText(inpLambda2.doubleValue()+"");
    }

    /**
     * @return the inpLambda3
     */
    public String getSaftyFactor() {
        return inpLambda3.getText();
    }

    /**
     * @param inpLambda3 the inpLambda3 to set
     */
    public void setSaftyFactor(Double inpLambda3) {
        this.inpLambda3.setText(inpLambda3.doubleValue()+"");
    }

    /**
     * @return the inpMTTR1
     */
    public String getInpMTTR1() {
        return inpMTTR1.getText();
    }

    /**
     * @param inpMTTR1 the inpMTTR1 to set
     */
    public void setInpMTTR1(Double inpMTTR1) {
        this.inpMTTR1.setText(inpMTTR1.doubleValue()+"");
    }

    /**
     * @return the inpPTP1
     */
    public String getInpPTP1() {
        return inpPTP1.getText();
    }

    /**
     * @param inpPTP1 the inpPTP1 to set
     */
    
    public void setInpPTP1(Double inpPTP1) {
        this.inpPTP1.setText(inpPTP1.doubleValue()+"");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpLambda2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        lblSum1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        comboVoting1 = new javax.swing.JComboBox<>();
        inpLambda1 = new javax.swing.JTextField();
        inpCCF1 = new javax.swing.JTextField();
        inpDC1 = new javax.swing.JTextField();
        inpMTTR1 = new javax.swing.JTextField();
        comboMTTR1 = new javax.swing.JComboBox<>();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        inpPTP1 = new javax.swing.JTextField();
        comboPTP1 = new javax.swing.JComboBox<>();
        inpLambda3 = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 0, 0));
        jLabel86.setText("Lambda  =");
        jLabel86.setToolTipText("Failure Rate (hr)");

        jLabel87.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(0, 0, 0));
        jLabel87.setText("CCF  =");
        jLabel87.setToolTipText("Common Cause Failure");

        jLabel88.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 0, 0));
        jLabel88.setText("Voting  =");
        jLabel88.setToolTipText("Sil Architecture");

        jLabel89.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(0, 0, 0));
        jLabel89.setText("DC  =");
        jLabel89.setToolTipText("Diagnosis Coverage");

        jLabel94.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 0, 0));
        jLabel94.setText("MTTR  =");
        jLabel94.setToolTipText("Mean Time To Restore (hour)");

        jLabel96.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 0, 0));
        jLabel96.setText("<html>\n" +
            "<body>\n" +
            "\n" +
            "<p>PFD<sub>AVG</sub> = </p>\n" +

            "\n" +
            "</body>\n" +
            "</html>");
        jLabel96.setToolTipText("Average probability of failure  on demand");

        lblSum1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSum1.setForeground(new java.awt.Color(0, 0, 0));
        lblSum1.setText("---------------------------------");

        comboVoting1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboVoting1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1oo1", "1oo2", "2oo2", "1oo2D", "2oo3" }));
        comboVoting1.setEnabled(false);
        comboVoting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVoting1ActionPerformed(evt);
            }
        });

        inpLambda1.setToolTipText("");

        inpDC1.setToolTipText("");

        inpMTTR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpMTTR1ActionPerformed(evt);
            }
        });

        comboMTTR1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hr", "days", "weeks" }));

        jLabel90.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(0, 0, 0));
        jLabel90.setText("%");

        jLabel91.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(0, 0, 0));
        jLabel91.setText("%");

        jLabel92.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(0, 0, 0));
        jLabel92.setText("PTP  =");
        jLabel92.setToolTipText("Proof test  interval (month)");

        comboPTP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month(s)", "year(s)" }));

        jLabel93.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 0, 0));
        jLabel93.setText("%");

        jLabel95.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 0, 0));
        jLabel95.setText("Safety Factor  =");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel87, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel89, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel94, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel92, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel95, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inpLambda1)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(inpCCF1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel90))
                            .addComponent(comboVoting1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inpPTP1)
                                    .addComponent(inpMTTR1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboMTTR1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboPTP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inpLambda3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpDC1))
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel91))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel93))))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel96)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator5)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(inpLambda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpLambda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel95))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(inpCCF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpDC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVoting1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMTTR1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inpMTTR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inpPTP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSum1))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboVoting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVoting1ActionPerformed

    }//GEN-LAST:event_comboVoting1ActionPerformed

    private void inpMTTR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpMTTR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpMTTR1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          int index = componentList.getSelectedIndex();
          DefaultListModel<Components> listcomModal= ((DefaultListModel<Components>) componentsList.getModel());
        
          JOptionPane.showMessageDialog(null, name+" - "+index+"\n"+getInpLambda1()+"\n"+listcomModal.size());
          Components editComRef = listcomModal.elementAt(index);
          
          Components editCom = new Components();
          editCom.setComId(editComRef.getComId());
          editCom.setComType(editComRef.getComType());
          editCom.setComDescription(editComRef.getComDescription());
          editCom.setLamda(Double.parseDouble(getInpLambda1()));
          editCom.setSafetyRelevantFactor(Double.parseDouble(getSaftyFactor()));
          editCom.setCcf(Double.parseDouble(getInpCCF1()));
          editCom.setDc(Double.parseDouble(getInpDC1()));
          editCom.setMttr(Double.parseDouble(getInpMTTR1()));
          editCom.setPti(Double.parseDouble(getInpPTP1()));
        
          listcomModal.set(index, editCom);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMTTR1;
    private javax.swing.JComboBox<String> comboPTP1;
    private javax.swing.JComboBox<String> comboVoting1;
    private javax.swing.JTextField inpCCF1;
    private javax.swing.JTextField inpDC1;
    private javax.swing.JTextField inpLambda1;
    private javax.swing.JTextField inpLambda2;
    private javax.swing.JTextField inpLambda3;
    private javax.swing.JTextField inpMTTR1;
    private javax.swing.JTextField inpPTP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblSum1;
    // End of variables declaration//GEN-END:variables

    
}
