/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.topfield.view.calculators;

import com.topfield.controller.Equations;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Murali
 */
public class Evacuation_From extends javax.swing.JPanel {

    private EvacuationCalculator cal;
    /**
     * Creates new form Evacuation_From
     */
    public Evacuation_From(EvacuationCalculator cal) {
        initComponents();
        setPreferredSize(new java.awt.Dimension(500, 493));
        setBackground(new Color(174, 182, 191));
        setForeground(Color.white);
        this.cal = cal;
    }

    public double iterationPerson(int person, String trainClass){
      double res =0.0;
      
        if (trainClass.equals("first")) {
            res = Equations.EvacuationTime(person, Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField7.getText()), Double.parseDouble(jTextField3.getText()));
        } else if (trainClass.equals("family")) {
            res = Equations.EvacuationTime(person, Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField11.getText()), Double.parseDouble(jTextField3.getText()));
        }else if (trainClass.equals("single")) {
            res = Equations.EvacuationTime(person, Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField14.getText()), Double.parseDouble(jTextField3.getText()));
        }
       
      return res; 
    }
    
    public int getNoOfPassengers( String trainClass){
       int res =0;
       
        if (trainClass.equals("first")) {
            res = Integer.parseInt(jTextField8.getText());
        } else if (trainClass.equals("family")) {
            res = Integer.parseInt(jTextField10.getText());
        }else if (trainClass.equals("single")) {
            res = Integer.parseInt(jTextField13.getText());
        }
    
      return res; 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel2.setText("Egress Capacity");

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 234, 248)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(600, 493));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Egress Capacity * ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        jTextField1.setText("0.0819");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        jTextField2.setText("1400");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 160, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Clear Door Width *");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Door opening time *");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, -1));

        jTextField3.setText("5");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Type of train");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 160, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, -1));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Types of disaster");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 160, -1));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Number of Cars");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 160, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 102, 150, 20));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Number of Passengers *");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, -1));

        jTextField7.setText("2");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, -1));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Number of Available doors *");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, -1));

        jTextField8.setText("102");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, -1));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Clear Door Width (mm)");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setText("Car 1");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 85, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setText("Car 2");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 85, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setText("Car 3");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 85, -1));

        jTextField10.setText("191");
        jTextField10.setToolTipText("");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 100, -1));

        jTextField11.setText("3");
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 100, -1));

        jTextField13.setText("229");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 100, -1));

        jTextField14.setText("4");
        add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 100, -1));
        add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 100, -1));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Evacuation Form");
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(136, 24));
        jLabel14.setRequestFocusEnabled(false);
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        jLabel15.setText("s");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 116, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate Evacuation time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 466, 269, -1));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 466, 51, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIME CRITICAL", "NON TIME CRITICAL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 81, 150, 20));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel18.setOpaque(true);
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 24));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel19.setOpaque(true);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 24));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel20.setOpaque(true);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 100, 24));

        jLabel22.setText("Person/mm- min");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 116, -1));

        jLabel23.setText("mm");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 116, -1));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("(*) indicates mandatory fields");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DecimalFormat df = new DecimalFormat("#.####");
        
         try {
         Double res1 = Equations.EvacuationTime(Integer.parseInt(jTextField8.getText()), Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField7.getText()), Double.parseDouble(jTextField3.getText()));
         Double res2 = Equations.EvacuationTime(Integer.parseInt(jTextField10.getText()), Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField11.getText()), Double.parseDouble(jTextField3.getText()));
         Double res3 = Equations.EvacuationTime(Integer.parseInt(jTextField13.getText()), Double.parseDouble(jTextField1.getText()), Double.parseDouble(jTextField2.getText()), Integer.parseInt(jTextField14.getText()), Double.parseDouble(jTextField3.getText()));
         jLabel19.setText(""+df.format(res1)+ "s");
         jLabel20.setText(""+df.format(res2)+ "s");
         jLabel18.setText(""+df.format(res3)+ "s");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Please fill the mandatory(*) fields with suitable values "/*+e.getMessage()*/);  
          jLabel19.setText("");
          jLabel20.setText("");
          jLabel18.setText("");
        }
 
         cal.generateChart(cal.createDataset());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
