server:
  port: 8081
spring:
  application:
    name: stem
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    password: example
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


stem:
  signing-key: "exampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKeyexampleSigningKey"